on:
  push:
    branches:
      - main

name: Handle Release
jobs:
  generate:
    permissions:
      contents: write
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Generate the artifacts
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: ./.github/build
      # - name: Set env
      #   run: echo "RELEASE_VERSION=v$(npm pkg get version | tr -d '"')" >> $GITHUB_ENV
      # - name: Upload the artifacts
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     INPUT_ARGS: ./dist/jsq
      #     INPUT_RELEASEID: ${{ env.RELEASE_VERSION }}
      #   run: ./.github/upload
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./dist/jsq
